### ISSUE TITLE
Sergius tends to shoot to the right while still dealing me damage

### ISSUE THREAD

**Issue by Pawonashi** [qndel/TchernobogBugTracker#12]
As in the title - I didn't encounter problem like this with any other enemy. Here's a video proof showing situation like this.

https://youtu.be/wfsSP13UGTw

Seems like this is a graphical glitch.

**Comment by qndel** [comment]
Fixed in 0.2.0 - same issue as old lightning enchanted monsters - it actually fires a circle but doesn't pass full information so you see only some of the missiles (in this case ... one while the spell is a nova)
Thanks for finding this one :)
![image](https://user-images.githubusercontent.com/14297035/105217217-de01b880-5b53-11eb-8419-8c9f67bacec7.png)
