### ISSUE TITLE
butcher movie causes freeze/crush on multiplayer

### ISSUE THREAD

**Issue by MisoPaste** [qndel/TchernobogBugTracker#6]
when i got nearby butcher room (butcher movie start) on multiplayer, host and client freeze.
- i'm playing 2-3 PCs on my LAN.
- i haven't got this issue on singleplayer.

this issue is multiplayer only perhaps.

**Comment by qndel** [comment]
works fine for me, not enough info

**Comment by MisoPaste** [comment]
need movie for prove ?
ill up YT if you want (but takes few mins, sry)

**Comment by qndel** [comment]
No, I believe you, it's just that's not enough, it works for me, what else can I do? ;)
What version? What's your operating system? Does host have movies disabled or enabled? Does the other player have movies disabled or enabled? Does the crash happen if both have it disabled/enabled? What happens if host has movies enabled and the other player doesn't? What happens when the host has movies disabled and the other player has them enabled? ;)

**Comment by MisoPaste** [comment]
both are using 0.1.4a,ill check details (especially config on movie) and record.

**Comment by MisoPaste** [comment]
configuraton on each machines (both are using 0.1.4a)<br>

OS:Windows 7 Home (host/client)<br>
(host side)
shake effect -> off
play movies -> off
monster hit effects -> on
town walk -> 100%
moster description -> on
auto staff skill -> disabled<br>

(client side)
shake effect -> off
play movies -> off
monster hit effects -> on
town walk -> 100%
moster description -> on
auto staff skill -> disabled

(movie on YT)
https://www.youtube.com/watch?v=kTr0wor-E4g
movie is recorded by client side.<br>
(other details)
- both turn play movies on. -> freeze,not fixed
- turn on client only (host is off) -> freeze,not fixed
- turn on host only (host is off) -> freeze,not fixed
- this freezes occured all difficulties.

**Comment by qndel** [comment]
Fixed in 0.1.4b - if you happen to be one of the players that get a freeze on cutscenes, ask the host to turn movies off
